In [56]:
import numpy as np

Решим СЛАУ методом Гаусса

In [43]:
A_1 = np.array([[-5., 1, 4, 4],
              [0, -5, -1, 1],
              [-2, 2, 4, 2], 
              [2, -5, 2, -3]])

b_1 = np.array([28., -7, 8, -45])

In [45]:
A_2 = np.array([[2., -1, 2, -2, -1],
              [4, -1, -2, -3, 1],
              [3, -1, -3, -3, 1], 
              [3, 0, 4, -2, -4],
              [0, 1, -5, 3, -5]])

b_2 = np.array([10, -10, 1, 17, -26])

In [14]:
def print_itter(A, b):
    print(A)
    print(b)
    print(' ')

In [55]:
def direct_move(A, b):    
    n_strings = A.shape[0]
    n_columns = A.shape[1]
    
    for i in range(n_strings - 1):
        denominator = A[i][i]
        if denominator == 0:
            continue
        
        A[i] = A[i] / denominator
        b[i] = b[i] / denominator
        
        for j in range(n_strings - 1, i, -1): 
            b[j] = b[j] - A[j][i] * b[i]
            A[j] = A[j] - A[j][i] * A[i]
        #print_itter(A, b)
        
    return A, b

In [2]:
def back_move(A, b):
    X = [0 for i in range(b.shape[0])]
    
    for i in range(b.shape[0] - 1, -1, -1):
        X[i] = (- np.sum(X * A[i]) + b[i]) / A[i][i]
        
    return np.array(X).round(3)

In [28]:
def method_Gauss(A, b):
    result_direct_move = direct_move(A, b) 
    return back_move(result_direct_move[0], result_direct_move[1])    

In [38]:
roots_1 = method_Gauss(A_1, b_1)

[[ 1.  -0.2 -0.8 -0.8]
 [ 0.  -5.  -1.   1. ]
 [ 0.   1.6  2.4  0.4]
 [ 0.  -4.6  3.6 -1.4]]
[ -5.6  -7.   -3.2 -33.8]
 
[[ 1.   -0.2  -0.8  -0.8 ]
 [-0.    1.    0.2  -0.2 ]
 [ 0.    0.    2.08  0.72]
 [ 0.    0.    4.52 -2.32]]
[ -5.6    1.4   -5.44 -27.36]
 
[[ 1.         -0.2        -0.8        -0.8       ]
 [-0.          1.          0.2        -0.2       ]
 [ 0.          0.          1.          0.34615385]
 [ 0.          0.          0.         -3.88461538]]
[ -5.6          1.4         -2.61538462 -15.53846154]
 


In [39]:
print('Корни: ', roots_1)

Корни:  [-5.  3. -4.  4.]


Проверим решение: 

In [44]:
np.linalg.solve(A_1, b_1)

array([-5.,  3., -4.,  4.])

In [46]:
roots_2 = method_Gauss(A_2, b_2)

[[ 1.  -0.5  1.  -1.  -0.5]
 [ 0.   1.  -6.   1.   3. ]
 [ 0.   0.5 -6.   0.   2.5]
 [ 0.   1.5  1.   1.  -2.5]
 [ 0.   1.  -5.   3.  -5. ]]
[  5 -30 -14   2 -26]
 
[[ 1.  -0.5  1.  -1.  -0.5]
 [ 0.   1.  -6.   1.   3. ]
 [ 0.   0.  -3.  -0.5  1. ]
 [ 0.   0.  10.  -0.5 -7. ]
 [ 0.   0.   1.   2.  -8. ]]
[  5 -30   1  47   4]
 
[[ 1.         -0.5         1.         -1.         -0.5       ]
 [ 0.          1.         -6.          1.          3.        ]
 [-0.         -0.          1.          0.16666667 -0.33333333]
 [ 0.          0.          0.         -2.16666667 -3.66666667]
 [ 0.          0.          0.          1.83333333 -7.66666667]]
[  5 -30   0  47   4]
 
[[  1.          -0.5          1.          -1.          -0.5       ]
 [  0.           1.          -6.           1.           3.        ]
 [ -0.          -0.           1.           0.16666667  -0.33333333]
 [ -0.          -0.          -0.           1.           1.69230769]
 [  0.           0.           0.           0.         -10.

In [47]:
print('Корни: ', roots_2)

Корни:  [-11.1   2.7   1.1 -14.4  -3.9]


Проверим решение:

In [48]:
np.linalg.solve(A_2, b_2)

array([-11.1,   2.7,   1.1, -14.4,  -3.9])